# Generated by Django 5.0.4 on 2024-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_product_average_rating_product_reviews_review_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='product_reviews+', to='commerce.review'),
        ),
        migrations.AlterField(
            model_name='store',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='store_reviews+', to='commerce.review'),
        ),
    ]
