# Generated by Django 5.0.4 on 2024-04-16 14:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_product_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='wallpaper',
            field=cloudinary.models.CloudinaryField(default='/assets/default_wallpaper.png', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
