# Generated by Django 5.0.4 on 2024-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_store_wallpaper_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='avatar/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='product/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='store',
            name='wallpaper',
            field=models.ImageField(default=None, upload_to='wallpaper/%Y/%m'),
        ),
    ]
