# Generated by Django 5.0.4 on 2024-04-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_remove_user_avatars_user_avatar_alter_product_image_and_more'),
    ]

    operations = [
    ]
