# Generated by Django 5.0.4 on 2024-04-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_auto_20240416_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='wallpaper',
        ),
    ]
