# Generated by Django 5.0.4 on 2024-04-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_store_wallpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='wallpaper',
        ),
    ]
