# Generated by Django 5.0.4 on 2024-04-17 13:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_remove_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
