# Generated by Django 5.0.4 on 2024-04-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_alter_product_description_alter_store_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
