# Generated by Django 5.0.4 on 2024-05-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='store',
            name='reviews',
        ),
    ]
