# Generated by Django 5.0.4 on 2024-05-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_remove_product_reviews_remove_store_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='store',
            name='average_rating',
        ),
    ]
