# Generated by Django 5.0.4 on 2024-05-05 13:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='wallpaper',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
        ),
    ]
