# Generated by Django 5.0.4 on 2024-05-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0028_alter_productvariant_color_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
