# Generated by Django 5.0.4 on 2024-05-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0029_orderdetail_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commerce.store'),
        ),
    ]
