# Generated by Django 5.0.4 on 2024-05-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_remove_orderdetail_order_remove_orderdetail_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='group_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.grouporderbystore'),
        ),
    ]
