# Generated by Django 5.0.4 on 2024-05-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0032_alter_orderdetail_group_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporderbystore',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.order'),
        ),
    ]
