# Generated by Django 5.0.4 on 2024-05-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_alter_grouporderbystore_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporderbystore',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commerce.order'),
        ),
    ]
